// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentBackend.Data;

#nullable disable

namespace RecruitmentBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711091741_AddAccountSecurityFields")]
    partial class AddAccountSecurityFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentBackend.Models.AIEvaluation", b =>
                {
                    b.Property<string>("EvaluationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("BlackboxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriteriaResultsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FitScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MatchedSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissingSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WhiteboxScore")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EvaluationID");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.ToTable("AIEvaluations");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Account", b =>
                {
                    b.Property<string>("AccountID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Application", b =>
                {
                    b.Property<string>("ApplicationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CVID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationID");

                    b.HasIndex("CVID");

                    b.HasIndex("JobID");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Branch", b =>
                {
                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Candidate", b =>
                {
                    b.Property<string>("CandidateID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultCvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultCvUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateCV", b =>
                {
                    b.Property<string>("CVID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CVExtractedSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CandidateID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certificates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("YearsOfExperience")
                        .HasColumnType("float");

                    b.HasKey("CVID");

                    b.ToTable("CandidateCVs");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachedFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobCriterion", b =>
                {
                    b.Property<string>("CriterionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("CriterionID");

                    b.HasIndex("JobID");

                    b.ToTable("JobCriteria");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobLevel", b =>
                {
                    b.Property<string>("JobLevelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JobLevelID");

                    b.HasIndex("ParentId");

                    b.ToTable("JobLevels");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobPosting", b =>
                {
                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("JDExtractedSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobLevelID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobRequirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxCandidates")
                        .HasColumnType("int");

                    b.Property<string>("PositionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecruiterID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalaryMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalaryMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("JobID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("JobLevelID");

                    b.ToTable("JobPostings");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Position", b =>
                {
                    b.Property<string>("PositionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Recruiter", b =>
                {
                    b.Property<string>("RecruiterID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecruiterID");

                    b.HasIndex("AccountID")
                        .IsUnique();

                    b.ToTable("Recruiters");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.RecruiterBranch", b =>
                {
                    b.Property<string>("RecruiterID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RecruiterID", "BranchID");

                    b.ToTable("RecruiterBranches");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.TalentPoolCandidate", b =>
                {
                    b.Property<string>("TalentPoolCandidateID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CandidateID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentAvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HighestAiScore")
                        .HasColumnType("int");

                    b.Property<string>("HighestScoreJobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighlightSkillsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestCVID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TalentPoolCandidateID");

                    b.HasIndex("CandidateID");

                    b.ToTable("TalentPoolCandidates");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.TalentPoolInteraction", b =>
                {
                    b.Property<string>("InteractionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AiScore")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByRecruiterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalentPoolCandidateID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InteractionID");

                    b.ToTable("TalentPoolInteractions");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.AIEvaluation", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Application", null)
                        .WithOne("AIEvaluation")
                        .HasForeignKey("RecruitmentBackend.Models.AIEvaluation", "ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Application", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.CandidateCV", "CandidateCV")
                        .WithMany()
                        .HasForeignKey("CVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentBackend.Models.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateCV");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Candidate", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Account", "Account")
                        .WithOne("Candidate")
                        .HasForeignKey("RecruitmentBackend.Models.Candidate", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Category", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobCriterion", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.JobPosting", "JobPosting")
                        .WithMany("Criteria")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobLevel", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.JobLevel", "ParentLevel")
                        .WithMany("SubLevels")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLevel");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobPosting", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("RecruitmentBackend.Models.JobLevel", "JobLevel")
                        .WithMany()
                        .HasForeignKey("JobLevelID");

                    b.Navigation("Category");

                    b.Navigation("JobLevel");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Position", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Category", "Category")
                        .WithMany("Positions")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Recruiter", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Account", "Account")
                        .WithOne("Recruiter")
                        .HasForeignKey("RecruitmentBackend.Models.Recruiter", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.RecruiterBranch", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Recruiter", null)
                        .WithMany("RecruiterBranches")
                        .HasForeignKey("RecruiterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Account", b =>
                {
                    b.Navigation("Candidate")
                        .IsRequired();

                    b.Navigation("Recruiter")
                        .IsRequired();
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Application", b =>
                {
                    b.Navigation("AIEvaluation")
                        .IsRequired();
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Category", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobLevel", b =>
                {
                    b.Navigation("SubLevels");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.JobPosting", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Recruiter", b =>
                {
                    b.Navigation("RecruiterBranches");
                });
#pragma warning restore 612, 618
        }
    }
}
